# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
