# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoter',
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(default='message', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quoter',
        ),
    ]
